### PR TITLE
Remove Jzy3d dependency

### LINKED ISSUE #137: Remove jzy3d dependency
Up until 0.5.2 we had in the core pom:
```
<repositories>
   <repository>
    <id>jzy3d</id> 
    <url>http://maven.jzy3d.org/releases</url>
   </repository>
</repositories>
```
That is missing in 0.5.3, after the refactoring done in #130 

Either way, there is a major problem even if we add that back: gradle doesn't read the repository from the pom, and therefore it is required to include http://maven.jzy3d.org/releases as a repository.

To solve the need of such requirement, I propose to remove the Jzy3D dependency and include the original source code, which comes from https://github.com/yonatang/JDT/tree/master/core, within FXyz-Core.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #137

### CODE REVIEW

**Review by AlmasB — APPROVED** [review]
All looks good. Wonder if we need `IOParsers`.

**Comment by nlisker** [comment]
I'm not sure why including the dependency just like we do in the other cases is a problem. Copying source code means it won't get updated. I'm not familiar with the code, so I can't comment on it.

**Comment by jperedadnr** [comment]
@nlisker yes, I've been trying to keep the dependency to Jzy3d, but it is quite inconvenient, since it is not in Maven Central, it requires adding their repository http://maven.jzy3d.org/releases, as Gradle doesn't resolve it even if it is included in the the pom.
Anyway, Jzy3d is already using a copy of the original source code from https://github.com/yonatang/JDT/tree/master/core, which is 9 years old, and hasn't been updated since, and they published it, which was the reason we used their fork instead.
Does this make sense?

@AlmasB I'd rather keep the whole code from https://github.com/yonatang/JDT/tree/master/core, even if we don't use `IOParsers`.

**Comment by nlisker** [comment]
If https://github.com/yonatang/JDT/tree/master/core is published can we not use it as a dependency?

**Comment by jperedadnr** [comment]
If the author publishes it to Maven Central, yes, we definitely will use it as dependency. But I doubt that's going to happen, as the code is 9 years old, and it was never published before.

**Comment by nlisker** [comment]
Oh, when you wrote "and they published it" I thought it was case.

If we can't solve it with dependencies then the patch if fine.

**Comment by jperedadnr** [comment]
Sorry, I was not clear. 

- Original code: https://github.com/yonatang/JDT/tree/master/core (never published)
- Jzy3d forked it into https://github.com/jzy3d/jzy3d-api/tree/master/jzy3d-jdt-core, and published it to http://maven.jzy3d.org/releases, which is what we have been using as dependency.

This PR removes the dependency from the Jzy3d fork, and adds the source code, so no external dependencies are required.

**Review by nlisker — APPROVED** [review]

**Pull request merged**
