### PR TITLE
Add jzy3d repository to pom

### PR DESCRIPTION
**Pull request by jperedadnr**

### CODE REVIEW

**Comment by AlmasB** [comment]
Is travis error related to this PR?

**Comment by jperedadnr** [comment]
Not directly to the pom changes, but to this change: https://github.com/FXyz/FXyz/pull/100/commits/53344324a1d18b77eff60faa225fc39bd30173dc
which is quite weird. I'll look into it

**Comment by jperedadnr** [comment]
Ok, the build works now, but we have a different issue: `sh: 0: Can't open /etc/init.d/xvfb`
Based on this [question](https://stackoverflow.com/questions/55674746/travis-sh-0-cant-open-etc-init-d-xvfb), it looks like we have to modify travis.
I'll do it (there is also an issue with publishing all but samples, #98 )

**Comment by jperedadnr** [comment]
Ok, we are green, we'll merge and do a minor release

**Pull request merged**
